services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskup_app
    volumes:
      - ./taskup-backend:/var/www/html/taskup-backend
    networks:
      - taskup-net
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: taskup_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./taskup-backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - taskup-net
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: taskup_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - taskup-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: taskup_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - taskup-net
    depends_on:
      - db

networks:
  taskup-net:

volumes:
  dbdata:
